### ISSUE TITLE
face detection pulls model file from unmaintained repo?

### ISSUE THREAD

**Issue by RoyalOughtness** [flathub/app.fotema.Fotema#70]
```
01:44:16.712 ERROR fotema::app::background::photo_detect_faces: Failed to extract photo faces: Other error: Failed to download file: error sending request for url (https://github.com/rustybuilder/model-zoo/raw/main/face-detection/blazefaces-640.onnx): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
```

the repo at https://github.com/rustybuilder/model-zoo appears to be an unofficial repo of binary files, and unassociated with fotema?

Ideally, fotema would work without network permissions altogether as well

**Comment by blissd** [comment]
Hi @RoyalOughtness. Thank you for your bug report. Fotema should not be pulling from that repo! I forked both rustyfaces and the model-zoo repos and models should be pulled form https://github.com/blissd/rust-faces-model-zoo.
I'll take a look to find what I missed and cut a fix so models are pulled from the right place.

As far as the network permissions goes--I agree. However, the model files can be large, and some users might not want to use them at all, and I'm not always sure what the licencing of models is and if they can be packed up with Fotema. Flatpak/flathub supports some sort of "external data" feature, so maybe that would be an option. However, I've not looked too hard at that.

**Comment by blissd** [comment]
I also agree that rustfaces (and its model-zoo) look largely unmaintained. I would like to rewrite the face detection to use a better supported library that rust-faces, but the trouble is the other libraries for this sort of thing were quite complicated, whereas rustfaces provided a very simple API that I could get going with right away.

Maybe at some point I'll figure out how to use [Hugging Face](https://github.com/huggingface/candle) for this. And if not that, maybe I can try OpenCV.

**Comment by blissd** [comment]
@RoyalOughtness do you know why the download failed? Did you disable network permissions with Flatseal?

**Comment by RoyalOughtness** [comment]
> @RoyalOughtness do you know why the download failed? Did you disable network permissions with Flatseal?

Yes, I was testing to see what needed it :smile:
